export enum ACTIONS_CONSTANTS {
  // Auth
  LOGIN = "LOGIN",
  REGISTER = "REGISTER",
  SET_AUTH = "SET_AUTH",
  SET_ERROR = "SET_ERROR",
  SET_AUTH_FETCHING = "SET_AUTH_FETCHING",
  SET_SUCCESS_AUTH_TOAST = "SET_SUCCESS_AUTH_TOAST",
  LOGOUT = "LOGOUT",

  // Todo
  GET_TODOS = "GET_TODOS",
  SET_TODOS = "SET_TODOS",
  ADD_TODO = "ADD_TODO",
  SET_TODOS_FETCHING = "SET_TODOS_FETCHING",
  SET_ERROR_TOAST = "SET_ERROR_TOAST",
  SET_SUCCESS_TOAST = "SET_SUCCESS_TOAST",
  CREATE_TODO = "CREATE_TODO",
  UPDATE_TODO = "UPDATE_TODO",
  SET_PAGE = "SET_PAGE",
  SET_SORT_BY = "SET_SORT_BY",
  SET_ORDER = "SET_ORDER",
}
